export type KejuaraanData = {
  status: "Disetujui" | "Ditolak" | "Diajukan Ulang" | "Sedang Diproses";
  id: string;
  nama: string;
  noSK: string;
  tanggalSK: string;
  kegiatan: string;
  tanggalKegiatan: string;
  penyelenggara: string;
  isValidated: boolean;
  validatedAt: string | null;
  createdAt: string;
  orkem: string;
  tingkatKejuaraan: string;
  tingkatPrestasi: string;
  dosen: string;
  keterangan?: string;
  piagamPenghargaan: string; // URL gambar publik
  fotoPenyerahanPiala: string; // URL gambar publik
  undanganKejuaraan: string; // URL text PDF publik
};
export const DUMMY_KEJUARAAN: KejuaraanData[] = [
  {
    status: "Disetujui",
    id: "dummyId1",
    nama: "John Doe",
    noSK: "028/K/BKA/II/2023",
    tanggalSK: "10 Februari 2023",
    kegiatan: "Seminar",
    tanggalKegiatan: "15 Februari 2023",
    penyelenggara: "Universitas ABC",
    isValidated: true,
    validatedAt: "18 Juli 2023, 08:45:00",
    createdAt: "01 Juli 2023, 09:00:00",
    orkem: "silat",
    tingkatKejuaraan: "Regional",
    tingkatPrestasi: "Juara 2",
    dosen: "Zainal Effendi",
    piagamPenghargaan: "https://example.com/piagam1.jpg",
    fotoPenyerahanPiala: "https://example.com/foto1.jpg",
    undanganKejuaraan: "https://example.com/undangan1.pdf",
  },
  {
    status: "Ditolak",
    id: "dummyId2",
    nama: "Jane Smith",
    noSK: "029/K/BKA/II/2023",
    tanggalSK: "11 Februari 2023",
    kegiatan: "Workshop",
    tanggalKegiatan: "10 Juli 2023",
    penyelenggara: "Institut XYZ",
    isValidated: false,
    validatedAt: null,
    createdAt: "20 Juni 2023, 12:00:00",
    orkem: "tari",
    tingkatKejuaraan: "Nasional",
    tingkatPrestasi: "Juara 1",
    dosen: "Andi Wijaya",
    piagamPenghargaan: "",
    fotoPenyerahanPiala: "",
    undanganKejuaraan: "",
  },
  {
    status: "Diajukan Ulang",
    id: "dummyId3",
    nama: "Michael Johnson",
    noSK: "030/K/BKA/II/2023",
    tanggalSK: "05 Februari 2023",
    kegiatan: "Lomba Catur",
    tanggalKegiatan: "20 Agustus 2023",
    penyelenggara: "Federasi Catur Indonesia",
    isValidated: false,
    validatedAt: null,
    createdAt: "05 Juli 2023, 08:30:00",
    orkem: "catur",
    tingkatKejuaraan: "Regional",
    tingkatPrestasi: "Juara 3",
    dosen: "Ahmad Rahman",
    piagamPenghargaan: "",
    fotoPenyerahanPiala: "",
    undanganKejuaraan: "https://example.com/undangan3.pdf",
  },
  {
    status: "Sedang Diproses",
    id: "dummyId4",
    nama: "Sarah Williams",
    noSK: "031/K/BKA/II/2023",
    tanggalSK: "12 Februari 2023",
    kegiatan: "Festival Seni",
    tanggalKegiatan: "30 September 2023",
    penyelenggara: "Komunitas Seni Budaya",
    isValidated: false,
    validatedAt: null,
    createdAt: "12 Juli 2023, 10:30:00",
    orkem: "seni",
    tingkatKejuaraan: "Nasional",
    tingkatPrestasi: "Juara Harapan",
    dosen: "Rina Anggraini",
    piagamPenghargaan: "",
    fotoPenyerahanPiala: "https://example.com/foto4.jpg",
    undanganKejuaraan: "",
  },
  {
    status: "Disetujui",
    id: "dummyId5",
    nama: "Kevin Lee",
    noSK: "032/K/BKA/II/2023",
    tanggalSK: "28 Juni 2023",
    kegiatan: "Turnamen Bulutangkis",
    tanggalKegiatan: "25 Oktober 2023",
    penyelenggara: "Klub Olahraga ABC",
    isValidated: true,
    validatedAt: "20 Juli 2023, 11:15:00",
    createdAt: "28 Juni 2023, 12:00:00",
    orkem: "bulutangkis",
    tingkatKejuaraan: "Internasional",
    tingkatPrestasi: "Juara 2",
    dosen: "Wahyu Susilo",
    piagamPenghargaan: "https://example.com/piagam5.jpg",
    fotoPenyerahanPiala: "https://example.com/foto5.jpg",
    undanganKejuaraan: "https://example.com/undangan5.pdf",
  },
  {
    status: "Diajukan Ulang",
    id: "dummyId6",
    nama: "Lisa Anderson",
    noSK: "033/K/BKA/II/2023",
    tanggalSK: "10 Juli 2023",
    kegiatan: "Festival Tari Tradisional",
    tanggalKegiatan: "05 November 2023",
    penyelenggara: "Sanggar Tari Nusantara",
    isValidated: false,
    validatedAt: null,
    createdAt: "10 Juli 2023, 07:30:00",
    orkem: "tari tradisional",
    tingkatKejuaraan: "Nasional",
    tingkatPrestasi: "Juara 1",
    dosen: "Budi Hartono",
    piagamPenghargaan: "https://example.com/piagam6.jpg",
    fotoPenyerahanPiala: "",
    undanganKejuaraan: "https://example.com/undangan6.pdf",
  },
  {
    status: "Disetujui",
    id: "dummyId7",
    nama: "Michael Jordan",
    noSK: "034/K/BKA/II/2023",
    tanggalSK: "20 Februari 2023",
    kegiatan: "Turnamen Bola Basket",
    tanggalKegiatan: "15 November 2023",
    penyelenggara: "Asosiasi Bola Basket Indonesia",
    isValidated: true,
    validatedAt: "25 Juli 2023, 14:30:00",
    createdAt: "20 Februari 2023, 13:00:00",
    orkem: "bola basket",
    tingkatKejuaraan: "Nasional",
    tingkatPrestasi: "Juara 1",
    dosen: "Robert Johnson",
    piagamPenghargaan: "https://example.com/piagam7.jpg",
    fotoPenyerahanPiala: "https://example.com/foto7.jpg",
    undanganKejuaraan: "https://example.com/undangan7.pdf",
  },
  {
    status: "Sedang Diproses",
    id: "dummyId8",
    nama: "Emma Watson",
    noSK: "035/K/BKA/II/2023",
    tanggalSK: "25 Februari 2023",
    kegiatan: "Kompetisi Menulis",
    tanggalKegiatan: "20 Desember 2023",
    penyelenggara: "Majalah Sastra Terbitan",
    isValidated: false,
    validatedAt: null,
    createdAt: "25 Februari 2023, 10:30:00",
    orkem: "sastra",
    tingkatKejuaraan: "Regional",
    tingkatPrestasi: "Juara Harapan",
    dosen: "Susan Adams",
    piagamPenghargaan: "",
    fotoPenyerahanPiala: "https://example.com/foto8.jpg",
    undanganKejuaraan: "https://example.com/undangan8.pdf",
  },
  {
    status: "Ditolak",
    id: "dummyId9",
    nama: "Robert Johnson",
    noSK: "036/K/BKA/II/2023",
    tanggalSK: "28 Februari 2023",
    kegiatan: "Turnamen Tenis Meja",
    tanggalKegiatan: "10 Januari 2024",
    penyelenggara: "Klub Olahraga XYZ",
    isValidated: false,
    validatedAt: null,
    createdAt: "28 Februari 2023, 09:00:00",
    orkem: "tenis meja",
    tingkatKejuaraan: "Regional",
    tingkatPrestasi: "Juara 3",
    dosen: "William Smith",
    piagamPenghargaan: "",
    fotoPenyerahanPiala: "",
    undanganKejuaraan: "",
  },
  {
    status: "Disetujui",
    id: "dummyId10",
    nama: "Alice Brown",
    noSK: "037/K/BKA/II/2023",
    tanggalSK: "02 Maret 2023",
    kegiatan: "Pentas Seni",
    tanggalKegiatan: "05 Januari 2024",
    penyelenggara: "Teater Abadi",
    isValidated: true,
    validatedAt: "15 Agustus 2023, 11:30:00",
    createdAt: "02 Maret 2023, 15:00:00",
    orkem: "seni teater",
    tingkatKejuaraan: "Nasional",
    tingkatPrestasi: "Juara 2",
    dosen: "Laura Anderson",
    piagamPenghargaan: "https://example.com/piagam10.jpg",
    fotoPenyerahanPiala: "https://example.com/foto10.jpg",
    undanganKejuaraan: "https://example.com/undangan10.pdf",
  },
];

export const KEJUARAAN_FORM = [
  {
    key: "nama",
    className: "col-span-1",
    placeholder: "Nama Mahasiswa",
    label: "Nama",
    value: "John Doe", // Contoh dummy data untuk nama mahasiswa.
  },
  {
    key: "noSK",
    className: "col-span-1",
    placeholder: "No SK",
    label: "No SK",
    value: "036/K/BKA/II/2023", // Contoh dummy data untuk nomor SK.
  },
  {
    key: "tanggalSK",
    className: "col-span-1",
    placeholder: "Tanggal SK",
    label: "Tanggal SK",
    value: "2023-07-15", // Contoh dummy data untuk tanggal SK.
  },
  {
    key: "dosen",
    className: "col-span-1",
    placeholder: "Dosen",
    label: "Dosen",
    value: "Dr. Jane Smith", // Contoh dummy data untuk dosen.
  },
  {
    key: "kegiatan",
    className: "col-span-1",
    placeholder: "Kegiatan",
    label: "Kegiatan",
    value: "Lomba Debat", // Contoh dummy data untuk kegiatan.
  },
  {
    key: "tanggalKegiatan",
    className: "col-span-1",
    placeholder: "Tanggal Kegiatan",
    label: "Tanggal Kegiatan",
    value: "2023-07-20", // Contoh dummy data untuk tanggal kegiatan.
  },
  {
    key: "penyelenggara",
    className: "col-span-1",
    placeholder: "Penyelenggara",
    label: "Penyelenggara",
    value: "Universitas ABC", // Contoh dummy data untuk penyelenggara.
  },
  {
    key: "orkem",
    className: "col-span-1",
    placeholder: "Orkem",
    label: "Orkem",
    value: "Internasional", // Contoh dummy data untuk orkem (organisasi kemahasiswaan).
  },
  {
    key: "tingkatKejuaraan",
    className: "col-span-1",
    placeholder: "Tingkat Kejuaraan",
    label: "Tingkat Kejuaraan",
    value: "Nasional", // Contoh dummy data untuk tingkat kejuaraan.
  },
  {
    key: "tingkatPrestasi",
    className: "col-span-1",
    placeholder: "Tingkat Prestasi",
    label: "Tingkat Prestasi",
    value: "Juara 1", // Contoh dummy data untuk tingkat prestasi.
  },
  {
    key: "piagamPenghargaan",
    className: "col-span-1",
    placeholder: "Piagam Penghargaan",
    label: "Piagam Penghargaan",
    type: "text",
    value: "", // Tidak ada dummy data untuk text piagam penghargaan karena ini adalah text.
  },
  {
    key: "fotoPenyerahanPiala",
    className: "col-span-1",
    placeholder: "Foto Penyerahan Piala",
    label: "Foto Penyerahan Piala",
    type: "text",
    value: "", // Tidak ada dummy data untuk text foto penyerahan piala karena ini adalah text.
  },
  {
    key: "undanganKejuaraan",
    className: "col-span-1",
    placeholder: "Undangan Kejuaraan",
    label: "Undangan Kejuaraan",
    type: "text",
    value: "", // Tidak ada dummy data untuk text undangan kejuaraan karena ini adalah text.
  },
  {
    key: "dokumenPendukung",
    className: "col-span-1",
    placeholder: "Dokumen Pendukung",
    label: "Dokumen Pendukung",
    type: "text",
    value: "", // Tidak ada dummy data untuk text dokumen pendukung karena ini adalah text.
  },
];
