export const NOTIFICATION = [
  {
    id: 1,
    name: "Pengajuan Prestasi",
    status: "Diajukan Ulang",
    color: "#FFD580",
    nama_mahasiswa: "Ahmad Naufal",
    createdAt: "Senin, 9 Januari 2023 pukul 09.30",
    isReaded: false,
    prodi: "Teknik Informatika",
    orkem: "Himpunan Mahasiswa Informatika",
    detail: "Prestasi Lomba Karya Tulis Ilmiah",
  },
  {
    id: 5,
    name: "Pengajuan Paten",
    status: "Baru",
    color: "#FF7070",
    nama_mahasiswa: "Eko Prestyo",
    createdAt: "Jumat, 21 April 2023 pukul 10.30",
    isReaded: false,
    prodi: "Biologi",
    orkem: "",
    detail: "Mengubah Air Menjadi Bensin",
  },
  {
    id: 6,
    name: "Pengajuan Prestasi",
    status: "Diajukan Ulang",
    color: "#FFD580",
    nama_mahasiswa: "Fajar Gumilang",
    createdAt: "Senin, 1 Mei 2023 pukul 13.45",
    isReaded: true,
    prodi: "Teknik Informatika",
    orkem: "Himpunan Mahasiswa Informatika",
    detail: "Prestasi Olimpiade Komputer Nasional",
  },
  {
    id: 2,
    name: "Pengajuan Haki",
    status: "Baru",
    color: "#FF7070",
    nama_mahasiswa: "Budi Sasmita",
    createdAt: "Selasa, 14 Februari 2023 pukul 11.45",
    isReaded: true,
    prodi: "Teknik Elektro",
    orkem: "",
    detail: "Hak Kekayaan Intelektual",
  },
  {
    id: 3,
    name: "Pengajuan PKM",
    status: "Baru",
    color: "#FF7070",
    nama_mahasiswa: "Citra Anggreaini",
    createdAt: "Rabu, 22 Maret 2023 pukul 14.00",
    isReaded: true,
    prodi: "Teknik Sipil",
    orkem: "",
    detail: "Program Kreativitas Mahasiswa",
  },
  {
    id: 4,
    name: "Pengajuan Beasiswa",
    status: "Baru",
    color: "#FF7070",
    nama_mahasiswa: "Dewi Puspita Sari",
    createdAt: "Kamis, 6 April 2023 pukul 16.15",
    isReaded: false,
    prodi: "Ilmu Komunikasi",
    orkem: "",
    detail: "",
  },
  {
    id: 7,
    name: "Pengajuan Haki",
    status: "Baru",
    color: "#FF7070",
    nama_mahasiswa: "Gita Mengkubuwono",
    createdAt: "Selasa, 16 Mei 2023 pukul 15.00",
    isReaded: false,
    prodi: "Teknik Elektro",
    orkem: "",
    detail: "Hak Kekayaan Intelektual",
  },
  {
    id: 8,
    name: "Pengajuan PKM",
    status: "Baru",
    color: "#FF7070",
    nama_mahasiswa: "Hani",
    createdAt: "Rabu, 24 Mei 2023 pukul 18.15",
    isReaded: true,
    prodi: "Teknik Sipil",
    orkem: "",
    detail: "Program Kreativitas Mahasiswa",
  },
  {
    id: 9,
    name: "Pengajuan Beasiswa",
    status: "Baru",
    color: "#FF7070",
    nama_mahasiswa: "Indra",
    createdAt: "Kamis, 8 Juni 2023 pukul 20.30",
    isReaded: true,
    prodi: "Ilmu Komunikasi",
    orkem: "",
    detail: "Beasiswa Pendidikan",
  },
  {
    id: 10,
    name: "Pengajuan Paten",
    status: "Baru",
    color: "#FF7070",
    nama_mahasiswa: "Joko",
    createdAt: "Jumat, 23 Juni 2023 pukul 09.45",
    isReaded: false,
    prodi: "Biologi",
    orkem: "",
    detail: "Paten Penemuan",
  },
];
